#!/usr/bin/env sh

set -ex

if [ -n "$1" ] && [ "$1" != "." ]; then
  echo "Running Shellcheck on $1"
  shift && shellcheck_original "$@"
else
  FIND_OUTPUT="$(find . -type f -name '*.sh' -not \( -path './.autodoc/*' -o -path '*/.cache/*' -o -path './.common*' -o -path '*/.config/*' -o -path './.git/*' -o -path './.modules/*' -o -path '*/.npm/*' -o -path '*/.pnpm-store/*' -o -path '*/.shared/*' -o -path '*/.task/*' -o -path './test/output-sample/*' -o -path '*/.venv/*' -o -path '*/.vscode/*' -o -path './build/*' -o -path './dist/*' -o -path '*/node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml -o -name package-lock.json -o -name poetry.lock -o -name '.variables.json' \) | paste -sd " ")"
  COUNT="$(echo "$FIND_OUTPUT" | wc -w)"
  if [ "$COUNT" != "0" ]; then
    echo "Running Shellcheck on $FIND_OUTPUT"
    # shellcheck disable=SC2086
    shellcheck_original $FIND_OUTPUT
  fi
fi
